version: "3.9"

services:
  django-todo:
    build: .
    container_name: django_todo
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - "${APP_PORT}:5050"
    env_file:
      - .env

networks:
